### ISSUE TITLE
is this support 12-word mnemonic?

### ISSUE THREAD

**Issue by hufengvia** [echovl/cardano-wallet#1]
it seems generate not the same as the bussiness Haskell one ,if the mnemonic is 12 words

the payment address its not the same with https://github.com/input-output-hk/cardano-addresses generate , which use the same mnemonic

**Comment by echovl** [comment]
Yes you're right.
I made a little mistake on the address path, it should work now.

**Comment by hufengvia** [comment]
> Yes you're right.
> I made a little mistake on the address path, it should work now.

its good ! I can generate stake-payment address base your code, thats cool
